from __future__ import annotations

from database.schema.runtime_schema import (
    CREATE_USERS_TABLE_SQL,
    CREATE_USER_PROFILES_TABLE_SQL,
    CREATE_USER_PREFERENCES_TABLE_SQL,
    CREATE_CONVERSATIONS_TABLE_SQL,
    CREATE_MESSAGES_TABLE_SQL,
    CREATE_RUNTIME_INDEXES_SQL,
)

V002_VERSION = 2
V002_NAME = "runtime_data"

UP_SQL = (
    CREATE_USERS_TABLE_SQL,
    CREATE_USER_PROFILES_TABLE_SQL,
    CREATE_USER_PREFERENCES_TABLE_SQL,
    CREATE_CONVERSATIONS_TABLE_SQL,
    CREATE_MESSAGES_TABLE_SQL,
    *CREATE_RUNTIME_INDEXES_SQL,
)

DOWN_SQL = (
    "DROP TABLE IF EXISTS messages",
    "DROP TABLE IF EXISTS conversations",
    "DROP TABLE IF EXISTS user_preferences",
    "DROP TABLE IF EXISTS user_profiles",
    "DROP TABLE IF EXISTS users",
)